name: CreateAzureWebApp     

env:
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project
  AZURE_WEBAPP_NAME: 'mmce-bmiPortal'
  AZURE_ENVIRONMENT: 'production'

on:
 workflow_dispatch:        

#on:
#  push:
#    paths-ignore:
#      - IAC-Templates/**
#      - .github/workflows/**
#    branches: [ master ]
#
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Branch name
      run: echo Branch=${GITHUB_REF##*/} >> $GITHUB_ENV

    - name: Output branch-name
      run: echo running on branch ${{ env.Branch }}
      
      # Checkout code
    - uses: actions/checkout@main
      with:
        ref: ${{ env.Branch }}

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Build for Release
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test TestProject1/TestProject1.csproj --no-restore --collect "Code coverage" -l:trx
  
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      with:
       name: MS Tests                  
       path: '**.trx'
       reporter: 'dotnet-trx'                     
       artifact: ''

    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 

# Deploy to Azure Web apps
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}                       
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        slot-name: ${{ secrets.AZURE_WEBAPP_SLOT }} 

