name: CreateAzureWebApp     

env:
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project
  AZURE_WEBAPP_NAME: 'mmce-bmiPortal'
  AZURE_ENVIRONMENT: 'production'
  AZURE_RG: 'CSDCA1v2'

on:
  push:
    paths-ignore:
      - IAC-Templates/**
#      - .github/workflows/**
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    environment: production
    steps:

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # blue/green
    - name: swap QA and production slots
      run: |
        az webapp deployment slot swap -n ${{ env.AZURE_WEBAPP_NAME }} -g ${{ env.AZURE_RG }} --slot QA --target-slot production
